language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - php vendor/bin/phpcs
  - php vendor/bin/phpunit --coverage-clover=build/logs/clover.xml

after_success:
  - php vendor/bin/codacycoverage clover

cache:
  directories:
    - vendor
